name: "Chromatic"
on: push

jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
